settings:
  title: '服务状态 | Hans362 ''s Lab'
  url: 'https://status.hans362.cn' # used for Slack messages
  logo: logo-256x256.png # image in ./public/ folder
  daysInHistogram: 45 # number of days you want to display in histogram
  collectResponseTimes: false # collects avg response times from CRON locations

  allmonitorsOperational: '所有系统运行正常'
  notAllmonitorsOperational: '系统存在故障'
  monitorLabelOperational: '正常'
  monitorLabelNotOperational: '故障'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '正常'
  dayInHistogramNotOperational: ' 故障报告' # xx incident(s) recorded

monitors:
  - id: hans362-s-homepage # unique identifier
    name: hans362.cn
    description: 'Hans362 ''s Homepage' # default=empty
    url: 'https://hans362.cn/' # URL to fetch
    method: GET # default=GET
    linkable: true # allows the title to be a link, default=true
 
  - id: hans362-s-blog # unique identifier
    name: blog.hans362.cn
    description: 'Hans362 ''s Blog' # default=empty
    url: 'https://blog.hans362.cn/' # URL to fetch
    method: GET # default=GET
    linkable: true # allows the title to be a link, default=true
    
  - id: hans362-s-lab # unique identifier
    name: lab.hans362.cn
    description: 'Hans362 ''s Lab' # default=empty
    url: 'https://lab.hans362.cn/' # URL to fetch
    method: GET # default=GET
    linkable: true # allows the title to be a link, default=true 
 